"""Command-line interface for generated-transformation validation."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from llm4mtl.transformation_execution.artifacts import archive_result
from llm4mtl.transformation_execution.discovery import (
    discover_transformations,
    discover_validated_suites,
    match_pairs,
)
from llm4mtl.transformation_execution.paths import (
    default_artifacts_root,
    default_etl_test_dir,
    default_results_root,
    default_transformations_root,
    default_validated_tests_root,
)
from llm4mtl.transformation_execution.results import write_results
from llm4mtl.transformation_execution.executor import validate_pair


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run reference-validated generated tests against generated ETL transformations."
    )
    parser.add_argument("--suite", action="append", type=Path, help="Validated suite directory; repeatable.")
    parser.add_argument("--transformation", action="append", type=Path, help="Generated .etl file; repeatable.")
    parser.add_argument("--task", help="Only evaluate this task, e.g. Tree2Graph.")
    parser.add_argument("--test-model", help="Only suites generated by this model.")
    parser.add_argument("--test-strategy", help="Only suites generated with this strategy.")
    parser.add_argument("--transformation-model", help="Only transformations generated by this model.")
    parser.add_argument("--transformation-strategy", help="Only transformations generated with this strategy.")
    parser.add_argument("--validated-tests-root", type=Path, default=default_validated_tests_root())
    parser.add_argument("--transformations-root", type=Path, default=default_transformations_root())
    parser.add_argument("--etl-test-dir", type=Path, default=default_etl_test_dir())
    parser.add_argument("--artifacts-root", type=Path, default=default_artifacts_root())
    parser.add_argument("--results-root", type=Path, default=default_results_root())
    parser.add_argument("--timeout", type=int, default=240, help="Maven timeout per pair in seconds.")
    parser.add_argument(
        "--overwrite-results",
        action="store_true",
        help="Replace per-task CSV files instead of appending this run.",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print matched pairs without executing Maven.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    suites = discover_validated_suites(
        args.validated_tests_root,
        explicit=args.suite,
        task=args.task,
        llm=args.test_model,
        strategy=args.test_strategy,
    )
    transformations = discover_transformations(
        args.transformations_root,
        explicit=args.transformation,
        task=args.task,
        llm=args.transformation_model,
        strategy=args.transformation_strategy,
    )
    pairs = match_pairs(suites, transformations)

    if not suites:
        print("No validated suites matched the selection.", file=sys.stderr)
        return 1
    if not transformations:
        print("No generated ETL transformations matched the selection.", file=sys.stderr)
        return 1
    if not pairs:
        print("No suite/transformation pairs share the same task.", file=sys.stderr)
        return 1

    if args.dry_run:
        for pair in pairs:
            print(f"Would validate {pair.transformation.path} with {pair.suite.path}")
        return 0

    archived_results = []
    for pair in pairs:
        print(
            f"Validating {pair.suite.task} | transformation={pair.transformation.llm}/{pair.transformation.strategy} "
            f"| suite={pair.suite.llm}/{pair.suite.strategy}/{pair.suite.suite_id}"
        )
        result = validate_pair(pair, args.etl_test_dir.resolve(), args.timeout)
        archived = archive_result(result, args.artifacts_root)
        archived_results.append(archived)
        print(
            f"  status={archived.status} compiles={archived.compiles} "
            f"executes={archived.executes} tests_pass={archived.tests_pass}"
        )
        if archived.error_summary:
            print(f"  error: {archived.error_summary}")
        print(f"  artifacts: {archived.artifact_dir}")

    for path in write_results(
        archived_results,
        args.results_root,
        append=not args.overwrite_results,
    ):
        print(f"Wrote {path}")

    return 0 if all(result.tests_pass for result in archived_results) else 1
